"""CLI for `hermes memory …` — filesystem initialization and project scaffolding.

This module provides:
  - `memory_init()`  — idempotent directory tree creation (the `memory init` subcommand)
  - `run_slash(rest)` — slash-command interface used from cli.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

# hermes_constants is in the hermes-agent root
try:
    from hermes_constants import get_hermes_home
except ImportError:
    # Fallback for when this module is imported outside the hermes-agent venv
    def get_hermes_home() -> str:
        return os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_ROOT_SUBDIRS = (
    "raw",
    "qmd",
    "daily",
    "projects",
    "entities",
    "dreams",
    "prompts",
    "exports",
    "backups",
    "config",
)

_STARTER_PROJECTS = (
    "hermes",
    "hermes-memory",
    "openclaw",
    "local-ai-lab",
    "personal-ai",
)

_PROJECT_STUBS = (
    "memory.md",
    "facts.md",
    "decisions.md",
    "open_questions.md",
    "timeline.md",
    "sources.md",
)


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------

def memory_init(home: Optional[str] = None) -> None:
    """Create or ensure the ``~/.hermes/memory/`` directory tree exists.

    Idempotent: if the tree already exists, this is a no-op.
    Does NOT create ``index/`` (that is created by the database schema init).

    Args:
        home: Path to the Hermes home directory. Defaults to get_hermes_home().
    """
    if home is None:
        home = get_hermes_home()

    root = Path(home)
    mem_root = root / "memory"

    # Create root if needed
    mem_root.mkdir(parents=True, exist_ok=True)

    # Create top-level subdirectories
    for name in _ROOT_SUBDIRS:
        (mem_root / name).mkdir(exist_ok=True)

    # Create starter project folders with stub files
    projects_dir = mem_root / "projects"
    projects_dir.mkdir(exist_ok=True)

    for project_name in _STARTER_PROJECTS:
        project_dir = projects_dir / project_name
        project_dir.mkdir(exist_ok=True)

        for stub in _PROJECT_STUBS:
            stub_path = project_dir / stub
            if not stub_path.exists():
                # Minimal markdown header stub
                title = stub.replace("_", " ").replace(".md", "").title()
                stub_path.write_text(f"# {title}\n\n")

    # Write README.md if it doesn't exist
    readme = mem_root / "README.md"
    if not readme.exists():
        readme.write_text(_BUILD_README(mem_root))


def _BUILD_README(mem_root: Path) -> str:
    """Build the README.md content."""
    subdirs = "\n".join(f"- `{d}/`" for d in _ROOT_SUBDIRS)
    projects = "\n".join(f"- `projects/{p}/`" for p in _STARTER_PROJECTS)

    return f"""\
# Hermes Local Memory — File Tree

This directory is the root of Hermes's local memory store.

## Top-level structure

{subdirs}

## Starter projects (auto-initialized)

{projects}

## Notes

- ``raw/`` — raw event JSONL files, date-segmented
- ``qmd/`` — quality-managed derived summaries
- ``daily/`` — daily digest files
- ``projects/`` — per-project working memory
- ``entities/`` — entity facts and relations
- ``dreams/`` — dreamer output (derived, rebuildable from raw)
- ``prompts/`` — saved prompt templates
- ``exports/`` — exported memory bundles
- ``backups/`` — manual and automated backups
- ``config/`` — schemas, event schemas, and configuration

``index/`` is created separately by ``hermes memory db init`` (schema init).

---
Auto-generated by `hermes memory init`. Do not edit manually.
"""


def run_slash(rest: str) -> str:
    """Execute ``hermes memory …`` and return formatted output.

    Args:
        rest: Everything after the ``memory`` keyword, e.g. ``"init"``.

    Returns:
        A string to display to the user.
    """
    tokens = rest.strip().split() if rest and rest.strip() else []
    sub = tokens[0] if tokens else None

    if sub == "init":
        home = get_hermes_home()
        was_existing = (Path(home) / "memory" / "projects").exists()

        memory_init()

        if was_existing:
            return "✓ ~/.hermes/memory/ is already initialized."

        # Count what was created
        root = Path(home) / "memory"
        created = [d.name for d in root.iterdir() if d.is_dir()]

        return f"✓ ~/.hermes/memory/ initialized.\n  Created: {', '.join(sorted(created))}"

    # Delegate all other subcommands to the hermes-local plugin CLI
    if sub in ("health", "db", "qdrant-init", "capture-test", "ls-sessions"):
        try:
            # Use direct file import (bypasses namespace issues with hyphenated dirs)
            import importlib.util
            import sys
            cli_path = Path(__file__).resolve().parent.parent / "plugins" / "memory" / "hermes-local" / "cli.py"
            module_name = "hermes_local_memory_cli"
            spec = importlib.util.spec_from_file_location(module_name, str(cli_path))
            if spec and spec.loader:
                cli_mod = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = cli_mod
                spec.loader.exec_module(cli_mod)
                return cli_mod.run_memory_subcommand(sub, " ".join(tokens[1:]))
        except Exception as e:
            return f"Error running 'memory {sub}': {e}\n(Hint: run 'hermes memory init' first.)"

    # Unknown subcommand — show full help
    try:
        # Use direct file import (bypasses namespace issues with hyphenated dirs)
        import importlib.util
        import sys
        cli_path = Path(__file__).resolve().parent.parent / "plugins" / "memory" / "hermes-local" / "cli.py"
        module_name = "hermes_local_memory_cli"
        spec = importlib.util.spec_from_file_location(module_name, str(cli_path))
        if spec and spec.loader:
            cli_mod = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = cli_mod
            spec.loader.exec_module(cli_mod)
            return cli_mod.run_memory_subcommand("help", "")
    except Exception:
        pass
    return (
        "Usage: /memory <subcommand>\n\n"
        "Subcommands:\n"
        "  init           — create ~/.hermes/memory/ directory tree\n"
        "  health         — show plugin health and configuration\n"
        "  db init        — initialize SQLite schema\n"
        "  capture-test   — inject synthetic turn end-to-end\n"
        "  ls-sessions    — list captured sessions\n"
    )


if __name__ == "__main__":
    # Allow running as: python -m hermes_cli.memory
    import sys

    rest = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else ""
    print(run_slash(rest))