#!/usr/bin/env python3
"""
migrate_from_holographic.py — Holographic → Hermes-Local migration script.

Usage:
    python scripts/migrate_from_holographic.py [--holo-db <path>] [--hl-db <path>] [--dry-run]

Options:
    --holo-db <path>    Path to holographic memory_store.db (default: ~/.hermes/memory_store.db)
    --hl-db   <path>    Path to hermes-local memory.sqlite (default: ~/.hermes/memory/index/memory.sqlite)
    --dry-run           Show what would migrate without writing to hermes-local

AC:
  AC1: All facts migrated with correct content_hash
  AC2: Idempotent via content_hash dedup (0 new rows on re-run)
  AC3: Schema introspection ignores extra/unknown columns (PRAGMA table_info)
  AC4: Report written to ~/.hermes/memory/exports/migration-holographic-{timestamp}.md
  AC5: Holographic DB never modified (read-only access verified)

DoD: --dry-run flag, entity mapping, HRR note in report

Author: hm-developer
Task: T-042
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ------------------------------------------------------------------ constants ---

# Resolve the actual .hermes directory:
# - In a dispatched worker: HERMES_HOME may be set to a profile dir (e.g. /.../hm-developer)
#   but the real data lives at the canonical ~/.hermes on this machine
# - Path.home() in this context resolves to the profile home dir (~/.hermes/profiles/hm-developer/home)
#   NOT the canonical ~/.hermes
# Fix: if ~/.hermes/profiles/<profile>/home/.hermes is the HERMES_HOME, use ~/.hermes instead
HERMES_HOME_FROM_ENV = os.environ.get("HERMES_HOME", "").strip()
if HERMES_HOME_FROM_ENV:
    # Check if HERMES_HOME is a profile subdirectory (ends in /home or /<profile>)
    # and the real .hermes exists at the canonical ~/.hermes level
    _profile_home_path = Path(HERMES_HOME_FROM_ENV)
    if _profile_home_path.name == "home" and (_profile_home_path.parent / ".hermes").exists():
        # HERMES_HOME points to a profile's home dir; canonical .hermes is sibling
        HERMES_HOME = _profile_home_path.parent
    else:
        HERMES_HOME = _profile_home_path
else:
    HERMES_HOME = Path.home() / ".hermes"

# Fallback: also check if canonical ~/.hermes has our data even when profile is set
_CANONICAL_HERMES = Path("/home/dmccarty/.hermes")
if _CANONICAL_HERMES.exists():
    _DEFAULT_HERMES = _CANONICAL_HERMES
else:
    _DEFAULT_HERMES = HERMES_HOME

DEFAULT_HOLO_DB = _DEFAULT_HERMES / "memory_store.db"
DEFAULT_HL_DB   = _DEFAULT_HERMES / "memory" / "index" / "memory.sqlite"
EXPORTS_DIR      = _DEFAULT_HERMES / "memory" / "exports"

REPORT_TEMPLATE = """# Migration Report: Holographic → Hermes-Local

**Timestamp:** {timestamp}
**Source:** {holo_db}
**Target:** {hl_db}
**Mode:** {mode}

## Counts

| Resource        | Holographic | Migrated | Skipped (duplicate) |
|-----------------|-------------|----------|---------------------|
| Facts           | {holo_facts}       | {migrated_facts}       | {skipped_facts}              |
| Entities        | {holo_entities}       | {migrated_entities}       | {skipped_entities}              |
| Fact-Entity Links | {holo_links}       | {migrated_links}       | -                    |

## Details

- **Mode:** {mode_desc}
- **HRR banks:** Will be recomputed via rebuild_all_vectors() post-migration
  (holographic HRR vectors are 1024d; hermes-local uses LMS embeddings instead)
- **Source refs:** All migrated facts tagged with `migration:holographic#fact_id=<old_id>`
- **Idempotency:** Re-running this script will produce 0 new rows (content_hash dedup)

## Notes

- Holographic DB was accessed **read-only** — no writes performed
- Schema introspection via PRAGMA table_info — extra columns in holographic are ignored
- If hermes-local already has facts with matching content_hash, they are skipped (not overwritten)
- Entities are mapped 1:1 by name; fact_entity links preserved

---
*Generated by hermes-memory T-042 migration script*
"""


# ------------------------------------------------------------------ helpers ---

def compute_content_hash(text: str) -> str:
    """Return SHA256 hex of fact text."""
    return hashlib.sha256(text.encode()).hexdigest()


def introspect_table(conn: sqlite3.Connection, table: str) -> list[dict]:
    """Return column metadata for a table using PRAGMA table_info."""
    cur = conn.execute(f"PRAGMA table_info({table})")
    return [dict(row) for row in cur.fetchall()]


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ------------------------------------------------------------------ core logic ---

def migrate(
    holo_db: Path,
    hl_db: Path,
    *,
    dry_run: bool = False,
    reporter: list[dict] | None = None,
) -> dict[str, int]:
    """
    Migrate facts + entities from holographic DB to hermes-local DB.

    Returns a dict with counts: {migrated_facts, skipped_facts, migrated_entities, ...}
    """
    reporter = reporter or []

    # ---- Connect to holographic (read-only) ----
    holo_conn = sqlite3.connect(f"file:{holo_db}?mode=ro", uri=True)
    holo_conn.row_factory = sqlite3.Row

    # ---- Connect to hermes-local (read-write) ----
    hl_conn = sqlite3.connect(str(hl_db))
    hl_conn.row_factory = sqlite3.Row
    # Ensure WAL for safety on networked filesystems
    try:
        hl_conn.execute("PRAGMA journal_mode=WAL")
    except sqlite3.Error:
        pass

    # ---- Introspect holographic columns ----
    holo_cols = {col["name"] for col in introspect_table(holo_conn, "facts")}
    mapped_cols = {"content", "category", "tags", "trust_score",
                   "retrieval_count", "helpful_count", "created_at", "updated_at"}
    extra_in_holo = holo_cols - mapped_cols
    if extra_in_holo:
        print(f"[migration] holographic has extra columns (will be ignored): {extra_in_holo}")

    # ---- Migrate entities first (needed for fact_entity links) ----
    entity_id_map: dict[int, int] = {}  # old_entity_id -> new_entity_id

    entity_rows = holo_conn.execute(
        "SELECT entity_id, name, entity_type, aliases, created_at FROM entities"
    ).fetchall()

    migrated_entities = 0
    skipped_entities  = 0

    for row in entity_rows:
        old_id = row["entity_id"]
        name   = row["name"]
        # Check if entity already exists by name
        existing = hl_conn.execute(
            "SELECT entity_id FROM entities WHERE name = ?", (name,)
        ).fetchone()
        if existing:
            entity_id_map[old_id] = existing["entity_id"]
            skipped_entities += 1
        else:
            cur = hl_conn.execute(
                """INSERT INTO entities (name, entity_type, aliases, created_at)
                   VALUES (?, ?, ?, ?)""",
                (name, row["entity_type"], row["aliases"] or "", row["created_at"]),
            )
            hl_conn.commit()
            entity_id_map[old_id] = cur.lastrowid
            migrated_entities += 1

    print(f"[migration] entities: {migrated_entities} migrated, {skipped_entities} skipped (existing)")

    # ---- Migrate facts ----
    fact_rows = holo_conn.execute(
        "SELECT fact_id, content, category, tags, trust_score, "
        "       retrieval_count, helpful_count, created_at, updated_at "
        "FROM facts ORDER BY fact_id"
    ).fetchall()

    migrated_facts   = 0
    skipped_facts    = 0
    migrated_links   = 0

    for row in fact_rows:
        fact_text    = row["content"]
        content_hash = compute_content_hash(fact_text)

        # Check idempotency: does this content_hash already exist in hermes-local?
        existing = hl_conn.execute(
            "SELECT fact_id FROM facts WHERE content_hash = ?", (content_hash,)
        ).fetchone()

        if existing:
            skipped_facts += 1
            # Still need to map fact_id for fact_entity links
            # We track old_id -> new_id via the fact_id_map (created below)
            continue

        # Build source_refs_json
        source_refs = [f"migration:holographic#fact_id={row['fact_id']}"]

        # Map: holographic.tags (comma-string) -> hermes-local.tags_json (JSON array)
        raw_tags = row["tags"] or ""
        tags_json = json.dumps([t.strip() for t in raw_tags.split(",") if t.strip()])

        # Map: holographic.trust_score -> hermes-local.trust_score AND confidence
        trust_score = row["trust_score"]
        confidence  = trust_score  # initial pin per TDD §16

        # Generate fact_id (TEXT format: fact:<sha256[:16]>)
        fact_id = f"fact:{content_hash[:16]}"

        # Map scope (no equivalent in holographic — default to 'general')
        scope = "general"

        created_at = row["created_at"] or now_iso()
        updated_at = row["updated_at"] or now_iso()

        if dry_run:
            # No write — just count
            migrated_facts += 1
        else:
            hl_conn.execute(
                """INSERT INTO facts
                   (fact_id, fact_text, content_hash, scope, category,
                    trust_score, confidence, status,
                    first_seen_at, last_confirmed_at,
                    source_refs_json, tags_json,
                    retrieval_count, helpful_count,
                    created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    fact_id,
                    fact_text,
                    content_hash,
                    scope,
                    row["category"] or "general",
                    trust_score,
                    confidence,
                    "active",
                    created_at,
                    updated_at,
                    json.dumps(source_refs),
                    tags_json,
                    row["retrieval_count"] or 0,
                    row["helpful_count"] or 0,
                    created_at,
                    updated_at,
                ),
            )
            hl_conn.commit()
            migrated_facts += 1

            # Map old fact_id -> new fact_id for fact_entity links
            old_fact_id = row["fact_id"]
            # We need to track this mapping; create a local dict
            fact_id_map = getattr(migrate, "_fact_id_map", {})
            fact_id_map[old_fact_id] = fact_id
            migrate._fact_id_map = fact_id_map  # type: ignore[attr-defined]

    # ---- Migrate fact_entity links ----
    link_rows = holo_conn.execute(
        "SELECT fact_id, entity_id FROM fact_entities"
    ).fetchall()

    fact_id_map: dict[int, str] = getattr(migrate, "_fact_id_map", {})

    for link in link_rows:
        old_fact_id  = link["fact_id"]
        old_entity_id = link["entity_id"]

        new_fact_id  = fact_id_map.get(old_fact_id)
        new_entity_id = entity_id_map.get(old_entity_id)

        if new_fact_id and new_entity_id:
            # Check if link already exists
            existing = hl_conn.execute(
                "SELECT 1 FROM fact_entities WHERE fact_id = ? AND entity_id = ?",
                (new_fact_id, new_entity_id),
            ).fetchone()
            if not existing:
                hl_conn.execute(
                    "INSERT OR IGNORE INTO fact_entities (fact_id, entity_id) VALUES (?, ?)",
                    (new_fact_id, new_entity_id),
                )
                hl_conn.commit()
                migrated_links += 1

    holo_conn.close()
    hl_conn.close()

    return {
        "migrated_facts":    migrated_facts,
        "skipped_facts":    skipped_facts,
        "migrated_entities": migrated_entities,
        "skipped_entities":  skipped_entities,
        "migrated_links":   migrated_links,
        "is_dry_run":       dry_run,
    }


def write_report(
    holo_db: Path,
    hl_db: Path,
    counts: dict[str, int],
    holo_counts: dict[str, int],
) -> Path:
    """Write migration report to memory/exports/."""
    EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    report_name = f"migration-holographic-{timestamp}.md"
    report_path = EXPORTS_DIR / report_name

    # Get holographic counts
    holo_conn = sqlite3.connect(f"file:{holo_db}?mode=ro", uri=True)
    holo_counts = {
        "facts": holo_conn.execute("SELECT COUNT(*) FROM facts").fetchone()[0],
        "entities": holo_conn.execute("SELECT COUNT(*) FROM entities").fetchone()[0],
        "links": holo_conn.execute("SELECT COUNT(*) FROM fact_entities").fetchone()[0],
    }
    holo_conn.close()

    content = REPORT_TEMPLATE.format(
        timestamp   = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        holo_db     = str(holo_db),
        hl_db       = str(hl_db),
        mode        = "DRY-RUN" if counts.get("is_dry_run") else "LIVE",
        is_dry_run  = counts.get("is_dry_run", False),
        mode_desc   = "DRY-RUN (no writes)" if counts.get("is_dry_run") else "LIVE (data written)",
        holo_facts  = holo_counts["facts"],
        migrated_facts   = counts.get("migrated_facts", 0),
        skipped_facts    = counts.get("skipped_facts", 0),
        holo_entities  = holo_counts["entities"],
        migrated_entities  = counts.get("migrated_entities", 0),
        skipped_entities  = counts.get("skipped_entities", 0),
        holo_links  = holo_counts["links"],
        migrated_links  = counts.get("migrated_links", 0),
    )

    report_path.write_text(content)
    print(f"[migration] Report written: {report_path}")
    return report_path


# ------------------------------------------------------------------ CLI ---

def main():
    parser = argparse.ArgumentParser(
        description="Migrate holographic memory to hermes-local",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--holo-db", type=Path, default=DEFAULT_HOLO_DB,
        help=f"Path to holographic memory_store.db (default: {DEFAULT_HOLO_DB})",
    )
    parser.add_argument(
        "--hl-db", type=Path, default=DEFAULT_HL_DB,
        help=f"Path to hermes-local memory.sqlite (default: {DEFAULT_HL_DB})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would migrate without writing to hermes-local",
    )

    args = parser.parse_args()

    # Validate inputs
    if not args.holo_db.exists():
        print(f"ERROR: Holographic DB not found at {args.holo_db}", file=sys.stderr)
        sys.exit(1)

    if not args.hl_db.exists():
        print(f"ERROR: Hermes-local DB not found at {args.hl_db}", file=sys.stderr)
        sys.exit(1)

    print(f"[migration] Starting migration")
    print(f"  Source: {args.holo_db} (read-only)")
    print(f"  Target: {args.hl_db}")
    print(f"  Mode:   {'DRY-RUN' if args.dry_run else 'LIVE'}")

    # Run migration
    counts = migrate(args.holo_db, args.hl_db, dry_run=args.dry_run)

    print(f"[migration] Done.")
    print(f"  Facts:    {counts['migrated_facts']} migrated, {counts['skipped_facts']} skipped (duplicate)")
    print(f"  Entities: {counts['migrated_entities']} migrated, {counts['skipped_entities']} skipped (existing)")
    print(f"  Links:    {counts['migrated_links']} migrated")

    # Write report (always, even dry-run)
    report_path = write_report(args.holo_db, args.hl_db, counts, {})

    if args.dry_run:
        print(f"\n[DRY-RUN] No data was written. Live run will migrate ~{counts['migrated_facts']} facts.")

    print(f"\nReport: {report_path}")
    sys.exit(0)


if __name__ == "__main__":
    main()